sac

diff --git a/applications/vaultwarden/overlays/production/backup/backup-cronjob.yaml b/applications/vaultwarden/overlays/production/backup/backup-cronjob.yaml
--- a/applications/vaultwarden/overlays/production/backup/backup-cronjob.yaml
+++ b/applications/vaultwarden/overlays/production/backup/backup-cronjob.yaml
@@ -56,30 +56,30 @@ spec:
                   - |
                     export RESTIC_VERSION=$(restic version | awk '{print $2}')
 
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/start
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_3_UUID/start
 
                     # Kubernetes, by default, uses the Pod name as the hostname, and since Pod names are random "no parent snapshot found, will read all files" occur as restic snapshots are distinguished by both path and host.
                     restic backup --host tryrocket.cloud --tag restic:$RESTIC_VERSION --tag vaultwarden:$VAULTWARDEN_VERSION /pg_dump /data
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_3_UUID/$?
 
                     restic check --read-data-subset 1/7
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_3_UUID/$?
 
                     restic forget --keep-daily 30 --keep-monthly 3 --keep-yearly 1 --prune
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_3_UUID/$?
               volumeMounts:
                 - name: vaultwarden-rwx-storage
                   mountPath: /data
                   readOnly: true
-                - name: vaultwarden-hetzner-subaccount-ssh-privatekey
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-privatekey
                   mountPath: /root/.ssh/id_ed25519
                   readOnly: true
                   subPath: id_ed25519
-                - name: vaultwarden-hetzner-subaccount-ssh-config
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-config
                   mountPath: /root/.ssh/config
                   readOnly: true
                   subPath: config
-                - name: vaultwarden-hetzner-subaccount-ssh-hosts
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-hosts
                   mountPath: /root/.ssh/hosts
                   readOnly: true
                   subPath: hosts
@@ -103,30 +103,30 @@ spec:
                   - |
                     export RESTIC_VERSION=$(restic version | awk '{print $2}')
 
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/start
+                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_1_UUID/start
 
                     # Kubernetes, by default, uses the Pod name as the hostname, and since Pod names are random "no parent snapshot found, will read all files" occur as restic snapshots are distinguished by both path and host.
                     restic backup --host tryrocket.cloud --tag restic:$RESTIC_VERSION --tag vaultwarden:$VAULTWARDEN_VERSION /pg_dump /data
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_1_UUID/$?
 
                     restic check --read-data-subset 1/7
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_1_UUID/$?
 
                     restic forget --keep-daily 30 --keep-monthly 3 --keep-yearly 1 --prune
-                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    #curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_IONOS_1_UUID/$?
               volumeMounts:
                 - name: vaultwarden-rwx-storage
                   mountPath: /data
                   readOnly: true
-                - name: vaultwarden-hetzner-subaccount-ssh-privatekey
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-privatekey
                   mountPath: /root/.ssh/id_ed25519
                   readOnly: true
                   subPath: id_ed25519
-                - name: vaultwarden-hetzner-subaccount-ssh-config
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-config
                   mountPath: /root/.ssh/config
                   readOnly: true
                   subPath: config
-                - name: vaultwarden-hetzner-subaccount-ssh-hosts
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-hosts
                   mountPath: /root/.ssh/hosts
                   readOnly: true
                   subPath: hosts
@@ -154,32 +154,32 @@ spec:
                   - |
                     ssh-keyscan -p 23 -f /root/.ssh/hosts >> /root/.ssh/known_hosts
 
-                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/start
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_HETZNER_UUID/start
 
                     export RESTIC_VERSION=$(restic version | awk '{print $2}')
 
                     # Kubernetes, by default, uses the Pod name as the hostname, and since Pod names are random "no parent snapshot found, will read all files" occur as restic snapshots are distinguished by both path and host.
                     restic backup --host tryrocket.cloud --tag restic:$RESTIC_VERSION --tag vaultwarden:$VAULTWARDEN_VERSION /pg_dump /data
-                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_HETZNER_UUID/$?
 
                     restic check --read-data-subset 1/7
-                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_HETZNER_UUID/$?
 
                     restic forget --keep-daily 30 --keep-monthly 3 --keep-yearly 1 --prune
-                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_UUID/$?
+                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$HC_HETZNER_UUID/$?
               volumeMounts:
                 - name: vaultwarden-rwx-storage
                   mountPath: /data
                   readOnly: true
-                - name: vaultwarden-hetzner-subaccount-ssh-privatekey
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-privatekey
                   mountPath: /root/.ssh/id_ed25519
                   readOnly: true
                   subPath: id_ed25519
-                - name: vaultwarden-hetzner-subaccount-ssh-config
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-config
                   mountPath: /root/.ssh/config
                   readOnly: true
                   subPath: config
-                - name: vaultwarden-hetzner-subaccount-ssh-hosts
+                - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-hosts
                   mountPath: /root/.ssh/hosts
                   readOnly: true
                   subPath: hosts
@@ -190,23 +190,23 @@ spec:
             - name: vaultwarden-rwx-storage
               persistentVolumeClaim:
                 claimName: vaultwarden-rwx-pvc
-            - name: vaultwarden-hetzner-subaccount-ssh-privatekey
+            - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-privatekey
               secret:
-                secretName: hetzner-subaccount-ssh-secret
+                secretName: hetzner-storagebox-bx11-fsn1-sftp-restic-secret
                 items:
                   - key: ssh-privatekey
                     path: id_ed25519
                 defaultMode: 384
-            - name: vaultwarden-hetzner-subaccount-ssh-config
+            - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-config
               secret:
-                secretName: hetzner-subaccount-ssh-secret
+                secretName: hetzner-storagebox-bx11-fsn1-sftp-restic-secret
                 items:
                   - key: ssh-config
                     path: config
                 defaultMode: 384
-            - name: vaultwarden-hetzner-subaccount-ssh-hosts
+            - name: hetzner-storagebox-bx11-fsn1-sftp-subaccount-vaultwarden-ssh-hosts
               secret:
-                secretName: hetzner-subaccount-ssh-secret
+                secretName: hetzner-storagebox-bx11-fsn1-sftp-restic-secret
                 items:
                   - key: ssh-hosts
                     path: hosts
